@url = https://.execute-api.us-east-1.amazonaws.com/prod/

GET {{url}}/empl?id=bffc6492-9c79-49dd-be7f-971481715ef4
###

POST {{url}}/empl
content-type: application/json

 {
    "name": "John",
    "possition": "enginner"
 }
###