@url = https://n4kxsma05j.execute-api.us-east-1.amazonaws.com/prod

GET {{url}}/empl?id=7a2233e7-b8cb-43d1-8a00-bc9ead3da5a5
###

POST {{url}}/empl
content-type: application/json

 {
    "name": "John",
    "possition": "enginner"
 }
###


# test wrong id
GET {{url}}/empl?id=1234
###

# @url = https://covr3k2a3h.execute-api.eu-west-1.amazonaws.com/prod/