@url = https://.execute-api.us-east-1.amazonaws.com/prod

GET {{url}}/empl?id=3f587052-220c-42ba-806b-9261552d2ad4
###

POST {{url}}/empl
content-type: application/json

 {
    "name": "John",
    "possition": "enginner"
 }
###


# test wrong id
GET {{url}}/empl?id=1234
###
